### ISSUE TITLE
This lesson should not have a lab format

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/selecting-single-elements-lab#38]
@cernanb 
This lab should have a readme format, rather than a lab format. It is a blocking issue for students that are just getting started.

**Comment by amievdj** [comment]
upvote

**Comment by kwebster2** [comment]
@fi-curriculum-team

**Comment by d-d-d-dalia** [comment]
yes

**Comment by maxwellbenton** [comment]
Hi @kwebster2,

I believe this issue was resolved in the summer of 2018 after the product team updated how lessons are interpreted (lessons without sub-folders are now interpreted as Readmes). I've confirmed that this lesson is displaying as a Readme now, so this issue should be resolved.

Thank you!
